# Generated by Django 3.0.4 on 2020-05-08 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_orderproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='orderproduct',
            name='price',
        ),
    ]
