# Generated by Django 3.0.4 on 2020-05-09 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20200508_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='amount',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='country',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
